variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.6.3-jdk-8

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository

.verify: &verify
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    - master

# Verify merge requests using JDK8
verify:jdk8:
  <<: *verify


.shared_deploy: &build_script
  script:
    - 'cp ci_settings.xml /root/.m2/settings.xml'
    - if [ ! -f ci_settings.xml ];
      then echo "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/project/packages/maven_repository.html#creating-maven-packages-with-gitlab-cicd for instructions.";
      fi
    - 'mvn clean package -s ci_settings.xml'
    - 'cp nodes.yaml target/nodes.yaml'

maven_build:
  stage: build
  <<: *build_script
  artifacts:
    paths:
      - target/*.jar
      - target/*.yaml
  only:
    - master
    - /^Release_\d+\.\d+\.\d+$/

