server:
  port: 4444

spring:
  jackson:
    serialization:
      indent_output: true

node:
  list:
    file: "./nodes.yaml"

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/"